services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak-gimnasio
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realm-gimnasio.json:/opt/keycloak/data/import/realm-gimnasio.json
    networks:
      - gimnasio-net

networks:
  gimnasio-net:
    driver: bridge
